### PR TITLE
Add try_as_raw_ptr/as_raw_ptr implementations for Symbol to convert to raw pointer

### PR DESCRIPTION
**Pull request by AlexanderSchuetz97**
see https://github.com/nagisa/rust_libloading/issues/153

### CODE REVIEW

**Comment by nagisa** [comment]
Sorry this took a while to get back to. I think I would still rather have plain inherent methods for the time being over trying to anticipate what the implementations of `TryInto/From` might look like in the future. An especially difficult part here is the `type Error = ()`. I would go for `Infallible` for these platforms, but even then it isn't particularly ergonomic from the perspective of the users who don't care about "those other platforms".

Let me know if you don't have time or desire to modify the PR, I'll try to find time for it myself in that case.

**Comment by AlexanderSchuetz97** [comment]
Ill do it until the end of the week.

**Comment by AlexanderSchuetz97** [comment]
I have updated the PR please review

**Review by nagisa — APPROVED** [review]

**Comment by AlexanderSchuetz97** [comment]
Thank you!

**Pull request merged**
